services:
  app:
    build: ./ 
    platform: linux/arm64/v8
    ports:
      - 8081:8080
    environment:
      - DB_HOST
      - DB_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - LINE_TOKEN
      - LINE_SECRET
      - CORS_ALLOW_ORIGIN
    networks:
      - spring-postgres

  db:
    image: postgres:14.5
    platform: linux/arm64/v8
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    expose:
      - 5432

volumes:
  db-data:

networks:
  spring-postgres:
